import pandas as pd
import os
data = pd.read_csv(os.path.abspath(os.path.dirname(os.getcwd())) + '/train.csv' )
print('--------查看缺失值-----------')
data.info()
print('--------数值型数据-----------')
print(data.describe())
print('--------存活数量-----------')
print(data.Survived.value_counts())
print('--------仓位人数-----------')
print(data.Pclass.value_counts())
print('--------港口登陆人数-----------')
print(data.Embarked.value_counts())
print('--------男女人数-----------')
print(data.Sex.value_counts())
print('--------间接亲属-----------')
print(data.SibSp.value_counts())
print('--------直接亲属-----------')
print(data.Parch.value_counts())