"""comfirmed

Revision ID: 741647815d25
Revises: 7b801af019fc
Create Date: 2018-02-04 23:03:14.489569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741647815d25'
down_revision = '7b801af019fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
