# Generated by Django 2.1.7 on 2019-03-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(max_length=16, verbose_name='TS代码')),
                ('symbol', models.CharField(db_index=True, max_length=8, unique=True, verbose_name='股票代码')),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='股票名称')),
                ('area', models.CharField(max_length=16, verbose_name='所在地域')),
                ('industry', models.CharField(max_length=16, verbose_name='所属行业')),
                ('fullname', models.CharField(max_length=64, verbose_name='股票全称')),
                ('enname', models.CharField(max_length=64, verbose_name='英文全称')),
                ('market', models.CharField(max_length=8, verbose_name='市场类型')),
                ('exchange', models.CharField(choices=[('SSE', '上交所'), ('SZSE', '深交所'), ('HKEX', '港交所')], max_length=8, verbose_name='交易所代码')),
                ('curr_type', models.CharField(max_length=8, verbose_name='交易货币')),
                ('list_status', models.CharField(choices=[('L', '上市'), ('S', '退市'), ('P', '暂停上市')], max_length=4, verbose_name='上市状态')),
                ('list_date', models.DateField(verbose_name='上市日期')),
                ('delist_date', models.DateField(verbose_name='退市日期')),
                ('is_hs', models.CharField(choices=[('N', '否'), ('H', '沪股通'), ('S', '深股通')], max_length=4, verbose_name='是否沪深港通标的')),
            ],
            options={
                'verbose_name': '股票列表',
                'db_table': 'share_list',
                'ordering': ['symbol'],
            },
        ),
    ]
